[package]
name = "fastvoted-reddit-bot"
version = "0.1.0"
authors = ["Matt Blessed <m@ttblessed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
