name: 'armv7: build and push docker image'

on:
  push:
    branches: [stable]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ARMv7_ARTIFACT_NAME: fastvoted_reddit_bot-Linux-armv7
  FASTVOTED_BOT_BIN_PATH: ./target/aarch64-unknown-linux-gnu/release/fastvoted_reddit_bot

jobs:
  build-aarch64-gnu:
    name: build aarch64 gnu
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: install cross
        run: |
          wget https://github.com/cross-rs/cross/releases/download/v0.2.4/cross-x86_64-unknown-linux-gnu.tar.gz
          sudo tar -zxf cross-x86_64-unknown-linux-gnu.tar.gz -C /usr/bin/
          sudo chmod 755 /usr/bin/cross /usr/bin/cross-util

      - run: cross build --bins --target aarch64-unknown-linux-gnu --release

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARMv7_ARTIFACT_NAME }}
          path: ${{ env.FASTVOTED_BOT_BIN_PATH }}

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: build-aarch64-gnu
    permissions:
      contents: read
      packages: write
    timeout-minutes: 10
    name: build and push docker image
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARMv7_ARTIFACT_NAME }}
          path: ${{ env.FASTVOTED_BOT_BIN_PATH }}

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to github container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea # v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build and push docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # v3.2.0
        with:
          context: .
          push: true
          file: Dockerfile.armv7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#platform
          platforms: linux/arm/v7
